trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    projects: '**/*.csproj'
    command: 'restore'
    includeNuGetOrg: true

- task: DotNetCoreCLI@2
  inputs:
    projects: '**/*Console.csproj'
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'sebcoles'
    repositoryName: 'sebcoles/VeraCustomTriage'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    tagPattern: 'v$(MajorVersion).$(MinorVersion).$(IncrementReleaseTagNumber)'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'